"""add experience fields to roles

Revision ID: 4d4370afaef1
Revises: 4cc727b21d9e
Create Date: 2026-05-10 11:50:12.512059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4370afaef1'
down_revision: Union[str, Sequence[str], None] = '4cc727b21d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('experience_level', sa.String(length=50), nullable=False))
    op.add_column('roles', sa.Column('experience_required_years', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'experience_required_years')
    op.drop_column('roles', 'experience_level')
    # ### end Alembic commands ###
