"""added 'created_at' in both models,added status in cadidate 

Revision ID: 73038c78702d
Revises: b46318c4df37
Create Date: 2026-05-09 23:42:44.923562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73038c78702d'
down_revision: Union[str, Sequence[str], None] = 'b46318c4df37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'created_at')
    op.drop_column('candidates', 'created_at')
    op.drop_column('candidates', 'status')
    # ### end Alembic commands ###
