"""add avatar_path to candidates

Revision ID: b70d57e71847
Revises: 052bb231a57a
Create Date: 2026-05-12 23:08:41.046142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70d57e71847'
down_revision: Union[str, Sequence[str], None] = '052bb231a57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'avatar_path')
    # ### end Alembic commands ###
