"""fix analysis table: add technical_score, rename resume_alignment

Revision ID: cfd0adfc12d1
Revises: 19de9c48ec93
Create Date: 2026-05-12 11:26:43.745396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd0adfc12d1'
down_revision: Union[str, Sequence[str], None] = '19de9c48ec93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('technical_score', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('resume_alignment', sa.JSON(), nullable=True))
    op.drop_column('analyses', 'resume_alingment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('resume_alingment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('analyses', 'resume_alignment')
    op.drop_column('analyses', 'technical_score')
    # ### end Alembic commands ###
